### ISSUE TITLE
Matmul regression in ToM compared to MLPerf branch.

### ISSUE THREAD

**Issue by MaheshRavishankar** [nod-ai/sdxl-scripts#106] opened 2024-10-15 23:01 UTC
For reproduction. 

Input Model:
https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/punet.mlir

Input data :
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.0.bin
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.1.bin
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.2.bin
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.3.bin
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.4.bin
 wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/inference_input.5.bin
wget https://sharkpublic.blob.core.windows.net/sharkpublic/sai/sdxl-punet/punet_weights.irpa 

I built IREE on main and used the TD script in https://github.com/nod-ai/sdxl-scripts/blob/shared/sdxl_on_main/int8-model/specs/attention_and_matmul_spec.mlir

Compilation command for IREE on main
```
iree-compile \
    --iree-execution-model=async-external \
    --iree-hal-target-backends=rocm \
    --iree-hip-target=gfx942 \
    --iree-hip-waves-per-eu=2 \
    --iree-codegen-gpu-native-math-precision=true \
    --iree-codegen-llvmgpu-use-vector-distribution \
    --iree-codegen-transform-dialect-library= \
    --iree-dispatch-creation-enable-aggressive-fusion=true \
    --iree-global-opt-propagate-transposes=true \
    --iree-llvmgpu-enable-prefetch=true \
    --iree-opt-aggressively-propagate-transposes=true \
    --iree-opt-const-eval=false \
    --iree-opt-outer-dim-concat=true \
    --iree-opt-data-tiling=false \
    --iree-preprocessing-pass-pipeline="builtin.module(util.func(iree-global-opt-raise-special-ops, iree-flow-canonicalize), iree-preprocessing-transpose-convolution-pipeline,  iree-preprocessing-pad-to-intrinsics, util.func(iree-preprocessing-generalize-linalg-matmul-experimental))" \
    --iree-vm-target-truncate-unsupported-floats \                                                                                                                                                                   ${PUNET_MODEL} \
    -o ${VMFB} \                                                               
```
Run Command : 
```
iree-benchmark-module \
    --device=hip:0 \
    --device_allocator=caching \
    --function=main \
    --hip_allow_inline_execution=true \
    --hip_use_stream=true \
    --input=1x4x128x128xf16=@inference_input.0.bin \
    --input=1xf16=@inference_input.1.bin \
    --input=2x64x2048xf16=@inference_input.2.bin \
    --input=2x1280xf16=@inference_input.3.bin \
    --input=2x6xf16=@inference_input.4.bin \
    --input=1xf16=@inference_input.5.bin \
    --module=${VMFB} \
    --parameters=model=punet_weights.irpa 
```

For compilation on MLPerf I used the same inputs/weights but used 
IREE Commit : https://github.com/iree-org/iree/tree/mlperf_v4.1_20240726
TD script : https://github.com/nod-ai/sdxl-scripts/blob/mlperf_v4.1_20240726/int8-model/specs/attention_and_matmul_spec.mlir

```
iree-compile
    --iree-execution-model=async-external \
    --iree-hal-target-backends=rocm \
    --iree-rocm-target-chip=gfx942 \
    --iree-rocm-waves-per-eu=2 \
    --iree-codegen-gpu-native-math-precision=true \
    --iree-codegen-llvmgpu-use-vector-distribution \
    --iree-codegen-transform-dialect-library=${TD_SPEC} \
    --iree-flow-enable-aggressive-fusion=true \                                                                                                                                                                      --iree-global-opt-propagate-transposes=true \
    --iree-llvmgpu-enable-prefetch=true \
    --iree-opt-aggressively-propagate-transposes=true \
    --iree-opt-const-eval=false \
    --iree-opt-outer-dim-concat=true \
    --iree-opt-data-tiling=false \
    --iree-preprocessing-pass-pipeline="builtin.module(util.func(iree-global-opt-raise-special-ops, iree-flow-canonicalize), iree-preprocessing-transpose-convolution-pipeline,  util.func(iree-preprocessing-pa\d-to-intrinsics), util.func(iree-preprocessing-generalize-linalg-matmul-experimental))" \
    --iree-vm-target-truncate-unsupported-floats \
    ${PUNET_MODEL} \
    -o ${VMFB} \
```

and same run command

There are in general slow down in performance. Particular issues are in the following three matmul dispatches

main$async_matmul_156_matmul_like_*
main$async_matmul_143_matmul_like_*
main$async_matmul_158_matmul_like_*

Attached is the IR log before and after strategy selection and lowering 

[sdxl_mlperf_matmul_143.dump.mlir.txt](https://github.com/user-attachments/files/17386619/sdxl_mlperf_matmul_143.dump.mlir.txt)
[sdxl_mlperf_matmul_156.dump.mlir.txt](https://github.com/user-attachments/files/17386620/sdxl_mlperf_matmul_156.dump.mlir.txt)
[sdxl_mlperf_matmul_158.dump.mlir.txt](https://github.com/user-attachments/files/17386622/sdxl_mlperf_matmul_158.dump.mlir.txt)
[sdxl_tom_matmul_143.dump.mlir.txt](https://github.com/user-attachments/files/17386623/sdxl_tom_matmul_143.dump.mlir.txt)
[sdxl_tom_matmul_156.dump.mlir.txt](https://github.com/user-attachments/files/17386625/sdxl_tom_matmul_156.dump.mlir.txt)
[sdxl_tom_matmul_158.dump.mlir.txt](https://github.com/user-attachments/files/17386626/sdxl_tom_matmul_158.dump.mlir.txt)

**Comment by MaheshRavishankar** [comment] 2024-10-15 23:10
I see that there is some differences in configuration setting. One of them has reordering set, one of them has prefetching enabled on main but not on MLPerf branch.

cc @kuhar  and @bangtianliu

**Comment by MaheshRavishankar** [comment] 2024-10-15 23:15
Attaching traces as well

![sdxl_mlperf](https://github.com/user-attachments/assets/704d15be-5953-41b1-bda8-ca9640362844)
![sdxl_tom](https://github.com/user-attachments/assets/326a27bb-4477-45d5-b427-db1d8db54977)

(well images of traces. I have the traces, but cant upload it)

**Comment by kuhar** [comment] 2024-10-16 00:44
@MaheshRavishankar is this CPX or SPX?

**Comment by MaheshRavishankar** [comment] 2024-10-16 00:53
I ran it in SpX mode

**Comment by kuhar** [comment] 2024-10-28 01:47
I looked at the top matmuls (143, 156, 158) from the first comment and the only significant difference I see is because of tuning.

When I disabled tuning on the mlperf branch (leaving only the attention spec in the TD file), the performance across these matmuls was very similar:

Dispatch | Name | MLPerf | MLPerf untuned | Main
-- | -- | -- | -- | --
143 | matmul_like_2x20x1024x64x1280_i8xi8xi32 | 47.7 | 83.3 | 83.6
156 | matmul_like_2x1024x10240x1280_i8xi8xi32 | 315 | 342 | 346
158 | matmul_like_2x1024x1280x5120_i8xi8xi32 | 174 | 174 | 176

I looked at the ISA and there are some accidental differences to scheduling / register allocation, but the only major difference I could see is that mlperf uses the mixed precision instructions like `v_fma_mixlo_f16` while main does not after the recent changes from @nirvedhmeshram.

I will produce a tuning script with the identical configs as what we used for mlperf to close the gap. But apart from that, I don't really see any new codegen regressions (at least in those 3 matmuls).

**Comment by kuhar** [comment] 2024-11-06 02:49
The last bit of perf difference seems to be caused by the workgroup reordering pass becoming a no-op after the flat workgroup size PR: https://github.com/iree-org/iree/pull/18947

https://github.com/iree-org/iree/blob/c2a5478553d8c35e74f0e4918a65333786106903/compiler/src/iree/compiler/Codegen/Common/GPU/WorkgroupReordering.cpp#L78-L82

With Y always equal to one, the reordering math gets folded away. While this shouldn't matter for CPX, it just happens that the folder code is a little bit better for whatever reason.

I will follow up and fix the workgroup reordering implementation for SPX, but I think we can close this issue already, given that we are almost at the parity with mlperf.

**Closed by kuhar** 2024-11-06 02:49 UTC
